#!/usr/bin/env python3
"""Generate src/font.h: glyph slot constants, the 1bpp->4bpp expansion LUT and the command
argument-count table.  The glyph shapes and widths themselves are read from the DS ROM at build
time (tools/dsfont.py) and stored in the ROM as data; the renderer finds them through the linker
symbols font_rows / font_w."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def gen():
    args = {int(k, 16): v for k, v in json.load(open(os.path.join(ROOT, 'data/cmd_args.json'))).items()}
    expand = []
    for m in range(256):
        v = 0
        for k in range(8):
            if (m >> (7 - k)) & 1: v |= 1 << (4 * k)
        expand.append(v)
    cmd = [args.get(c, 0) for c in range(0x80)]
    out = ['/* generated by tools/genfont.py */', '#pragma once', '#include "gba.h"',
           '#define FONT_NGLYPH 0x119', '#define FONT_MISSING 0x118',
           'extern const u16 font_rows[FONT_NGLYPH*16];   /* placed by the build (linker symbol) */',
           'extern const u8 font_w[FONT_NGLYPH];',
           'static const u32 expand_lut[256] = {' + ','.join(f'0x{v:08x}' for v in expand) + '};',
           'static const u8 cmd_args[0x80] = {' + ','.join(str(c) for c in cmd) + '};']
    open(os.path.join(ROOT, 'src/font.h'), 'w').write('\n'.join(out) + '\n')

if __name__ == '__main__':
    gen()
